# Generated by Django 3.2.5 on 2021-07-05 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_users_user_friend_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
