# Generated by Django 3.2.5 on 2021-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210712_1057'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='book',
        ),
        migrations.AddField(
            model_name='userlist',
            name='book',
            field=models.ManyToManyField(to='books.Book'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='list',
            field=models.CharField(choices=[('w', 'wishlist'), ('r', 'readlist'), ('s', 'shelflist')], max_length=20),
        ),
    ]
