# Generated by Django 3.2.5 on 2021-07-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210712_1057'),
        ('lists', '0002_auto_20210713_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='book',
            field=models.ManyToManyField(null=True, to='books.Book'),
        ),
    ]
