# Generated by Django 3.2.5 on 2021-07-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_authors'),
        ('lists', '0003_alter_userlist_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='book',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
